# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05cafedd6817200f32a5fe8a95433f94f091c12c04ce852ffddb19133a331a758d3c4277594ee117b93813c17baa174fd5e1be564aec04ffa1541d1799ee0029

test:
  secret_key_base: f9df6789747f87dd73717105d50d83e370a0f119a3393a7d92a9c13c372846f49096614f022cd7a776fb00c386a42882f322fc26a6c61b2a55c1a7c77fe1abc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
